application:
  replicas: 1
  image:
    name: felipecs8/qrcode-generator
    tag: v1
  service:
    type: ClusterIP
  clusterIssuer: "letsencrypt-prod"
  ingress:
    enabled: false
    hosts:
    - qrcode.127.0.0.1.nip.io
    ingressClassName: null
    tls:
      enabled: false
    sslRedirect:
      enabled: false