apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-conversor-temperatura
spec:
  replicas: {{ .Values.application.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-conversor-temperatura
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-conversor-temperatura
    spec:
      containers:
      - name: app
        image: {{ .Values.application.image.name }}:{{ .Values.application.image.tag }}
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5