application:
  replicas: 2
  image:
    name: felipecs8/conversor-temperatura
    tag: b416c3cf83a20d7c006b46a10673b0e571e53989
  service:
    type: ClusterIP
  canary:
    steps:
      - setWeight: 50
      - pause:
          duration: 60s
      - setWeight: 100
